### ISSUE TITLE
[Error] Lỗi mở file

### ISSUE THREAD

**Issue by ThaiDat** [phan-anh-hao/Project_Data_Science#2]
![image](https://user-images.githubusercontent.com/18527312/104577522-2caede80-568c-11eb-846c-f6d62097dec4.png)
Lỗi phát sinh khi chạy Notebook trên Docker
Đường dẫn đúng là 'Data/Data.csv'.
Mã nguồn hiện tại chỉ chạy được trên các hệ thống tự nhân diện chữ hoa thường (như Windows)

**Comment by phan-anh-hao** [comment]
Mình thay mặt nhóm cảm ơn bạn về vấn đê này, nhóm mình sẽ sửa lại code để có thể chạy được trên các hệ thống khác nhau.

Hào
