### ISSUE TITLE
[Question] Phụ thuộc kết quả và kích thức của hidden layer

### ISSUE THREAD

**Issue by ThaiDat** [phan-anh-hao/Project_Data_Science#3]
Cái này không hẳn là một issue.
![image](https://user-images.githubusercontent.com/18527312/104584551-591b2880-5695-11eb-8b17-d9afca129297.png)
Dựa vào heatmap thì sự tăng kích thước của hidden layer có ảnh hưởng lớn đến train loss và có quan hệ phụ thuộc với validation loss.

**Comment by phan-anh-hao** [comment]
Mình thay mặt nhóm mình sẽ nhận xét về heatmap này kỹ hơn.
Cảm ơn bạn đã đóng ý kiến cho nhóm mình.

Hào
