### ISSUE TITLE
[Improvement] Phương pháp sinh ngày tháng để lấy dữ liệu

### ISSUE THREAD

**Issue by ThaiDat** [phan-anh-hao/Project_Data_Science#4]
Hiện tại, để lấy API theo ngày từ metaweather, mã nguồn này cần sinh một danh sách những ngày khả dĩ một cách thủ công, lưu vào file và sau đó đọc file này lên lại. Về cơ bản file này không có giá trị lưu trữ (không mang thông tin gì hữu ích cả), lưu trữ sẽ tốn tài nguyên máy tính.
Nên xử lý trực tiếp, sinh ngày đến đâu lấy dữ liệu đến đó (có thể dùng python closure).

Bên cạnh đó, mã nguồn này tự implement lại việc sinh ngày tuần tự trong 4 năm liền, điều này tốt, nhưng không cần thiết, cũng không đảm bảo độ tin cậy cho người đọc. Có thể sửa lại như sau:
```python
from datetime import datetime, timedelta

d = datetime(year=2019,month=2,day=28)
one = timedelta(days=1)
next_day = d + one
```
![image](https://user-images.githubusercontent.com/18527312/104586166-ae583980-5697-11eb-9047-b7ffb9d26f9f.png)

**Comment by phan-anh-hao** [comment]
Mình thay mặt nhóm cảm ơn bạn về vấn đề thu thập dữ liệu này, vì thời gian thu thập dữ liệu khá lâu nên mình sẽ cải thiện điều này vào những project khác

Hào
